### ISSUE TITLE
change pull request merges from dev branch to master branch

### ISSUE THREAD

**Issue by bachittle** [prairir/Buoy#3]
#### Describe Problem
I personally believe it is redundant to make pull requests onto a separate dev branch, rather than making the requests directly on master. If big features need to be combined into a separate branch before merging into master, that can be done fairly easily regardless. The only benefit is CICD, and that is not set up yet. If any of y'all have better arguments for doing things this way, please specify so I can be on the same page. 

#### Suggest Changes
merge requests will go to master unless otherwise needed

#### Provide Examples
The pull request at https://github.com/prairir/Buoy/pull/2 could be changed to merge straight into master after code review, so that the request does not have to be reviewed twice.

**Comment by prairir** [comment]
I am closing this because it has been resolved by now only using the feature branches and the master branch
